// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtq65wXHOXksRPadTq_yUTHkgENQn5weQ',
    appId: '1:1001477861366:web:fd52bff939203cef59a1d7',
    messagingSenderId: '1001477861366',
    projectId: 'edu-connect-fe642',
    authDomain: 'edu-connect-fe642.firebaseapp.com',
    storageBucket: 'edu-connect-fe642.appspot.com',
    measurementId: 'G-TM955F8RK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijGzSs3LaUXpCCmH_IHQdLgh_8r_he3s',
    appId: '1:1001477861366:android:a970c16f8a8ebce859a1d7',
    messagingSenderId: '1001477861366',
    projectId: 'edu-connect-fe642',
    storageBucket: 'edu-connect-fe642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT61p42Rkh8zwCWyg3FFtG9VQvfqy73A4',
    appId: '1:1001477861366:ios:823587abfd9ea99759a1d7',
    messagingSenderId: '1001477861366',
    projectId: 'edu-connect-fe642',
    storageBucket: 'edu-connect-fe642.appspot.com',
    iosBundleId: 'com.example.eduProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT61p42Rkh8zwCWyg3FFtG9VQvfqy73A4',
    appId: '1:1001477861366:ios:823587abfd9ea99759a1d7',
    messagingSenderId: '1001477861366',
    projectId: 'edu-connect-fe642',
    storageBucket: 'edu-connect-fe642.appspot.com',
    iosBundleId: 'com.example.eduProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtq65wXHOXksRPadTq_yUTHkgENQn5weQ',
    appId: '1:1001477861366:web:e788ed255176a85259a1d7',
    messagingSenderId: '1001477861366',
    projectId: 'edu-connect-fe642',
    authDomain: 'edu-connect-fe642.firebaseapp.com',
    storageBucket: 'edu-connect-fe642.appspot.com',
    measurementId: 'G-4EJB0TFDNQ',
  );
}
